### PR TITLE
Fix #170: show total number of records

### LINKED ISSUE #170: Display the number of records in a collection
In the collection list of records we should display the total number of records.

### PR DESCRIPTION
**Pull request by leplatrem**
Fix #170

### CODE REVIEW

**Comment by glasserc** [comment]
I'm not crazy about this because of Kinto/kinto#1624.

**Comment by glasserc** [comment]
I disagree. I think if we don't merge this, it's still possible to essentially remove `Total-Records` from list-records responses. I think once we merge this, it's much harder to make such a change.

**Comment by leplatrem** [comment]
> I disagree. I think if we don't merge this, it's still possible to essentially remove Total-Records from list-records responses. I think once we merge this, it's much harder to make such a change.

Do you think we should have an explicit call to `collection.getTotalRecords()` instead?

**Comment by glasserc** [comment]
Yes, I would approve of that change.

**Comment by leplatrem** [comment]
screencast from 05-10-2018 15_54_03

I created another action to avoid locking the records loading just for that number

**Pull request merged**
