### PR TITLE
Add LGTM code quality badges

### PR DESCRIPTION
**Pull request by xcorail**
Hi there!

I thought you might be interested in adding these [code quality badges](https://lgtm.com/projects/g/Kinto/kinto-admin/ci/#badges) to your project. They will indicate a very high code quality to potential users and contributors.
You can also check the alerts discovered by [LGTM](https://lgtm.com/projects/g/Kinto/kinto-admin).

N.B.: I am on the team behind LGTM.com, I'd appreciate your feedback on this initiative, whether you're interested or not, if you find time to drop me a line. Thanks.

### CODE REVIEW

**Comment by leplatrem** [comment]
Thanks @xcorail for the offer.

@Natim @glasserc @peterbe  what do you think of this?

I don't mind adding the badges, but I'd rather prefer a PR check or similar...

**Comment by xcorail** [comment]
Hi @leplatrem 

Thanks for the feedback.

You can have PR check, it's free for open source projects, and it's a [one click operation](https://lgtm.com/projects/g/Kinto/kinto-admin/ci/). LGTM will analyse **immediately** the PR, and report any new problem (or fix). This is our recommended usage of LGTM.

Otherwise, the alerts check will be always there for you, with a repo poll once a day.

(For the sake of clarity: you are not obliged to add the badges to activate PR check and benefit from the service)

If you need any help, you can also ping us here: https://discuss.lgtm.com/
 
cc @Natim @glasserc @peterbe

**Comment by glasserc** [comment]
Personally, I'm not excited about a proprietary SaaS for code quality. 

I looked through the alerts on lgtm and most of them seem present in e.g. htmllint or eslint (with a react plugin).

We already have a badge that says our build passes. Any linting we want to do should hook into that.

I would prefer to close this.

**Comment by Natim** [comment]
I will let you guys decide I am +0 on this

**Pull request closed without merging**
