### PR TITLE
Improve typing of group state.

### PR DESCRIPTION
**Pull request by n1k0**
WiP. Playing with the awesome `flow coverage` command I've discovered we've been relying on some really generic types here and there.

### CODE REVIEW

**Comment by Natim** [comment]
@n1k0 wants to add Records and Collection before landing it.

**Comment by n1k0** [comment]
Won't do.

**Comment by glasserc** [comment]
Why not?

**Comment by n1k0** [comment]
Yeah indeed. Will make a general pass over types.

**Pull request merged**
