### PR TITLE
Fixes #73: Added support for Firefox Account authentication.

### LINKED ISSUE #73: Add support for Firefox Account authentication

### PR DESCRIPTION
**Pull request by n1k0**
This is WiP, refs #73.

Note: I needed to upgrade a bunch of dependencies because of a bug in react-router which has been fixed in latest version.

I've deployed the patch [to gh-pages](https://kinto.github.io/kinto-admin/), feedback welcome.

### CODE REVIEW

**Comment by Natim** [comment]
Does this request makes it possible to give a link with the basicauth setup for the kinto-admin directly?

**Comment by n1k0** [comment]
> Does this request makes it possible to give a link with the basicauth setup for the kinto-admin directly?

Not atm but it should be possible; but what would be the use case? Also I'm realizing having a public link logging you in automatically might not be a good idea...

**Comment by n1k0** [comment]
Well, okay sorry, I misread your comment (thought you were expecting to share an FxA auth link). So no, a link to setup basic auth automatically is not possible atm; Also that would mean having the password in the URL, which is concerning.

**Comment by Natim** [comment]
Yes but the security model with BasicAuth is to use a VPN to authenticate. So that would let people have a bookmark with their credentials that they can use once connected to the VPN.

**Comment by n1k0** [comment]
> Yes but the security model with BasicAuth is to use a VPN to authenticate. 

This is the security model for one project at Mozilla; should we expand this model to the community?

**Comment by Natim** [comment]
Yes no you are probably right.
Maybe an alternative that can prefill the server url and the username but still ask for the password?

**Comment by n1k0** [comment]
If we can live with having the form prefilled with server and username, excluding the password from the URL, yes that should be possible though. That's a good idea, please file an issue to have this addressed outside of this PR.

**Comment by Natim** [comment]
Yes ok

**Comment by leplatrem** [comment]
Auth worked like a charm \o/

Nit: combo of auth method is not affordant (no visual feedback that it is a combox, and not a field). Idea: Use radios ?
capture d ecran de 2016-05-24 11-42-33

Nit2: not username shown on top menu
capture d ecran de 2016-05-24 11-44-39

**Comment by Natim** [comment]
> Use radios ?

:+1: 

> no username shown on top menu

I have created https://github.com/Kinto/kinto/issues/641 about this one.

**Comment by n1k0** [comment]
> Idea: Use radios ?

Yeah, using radios is much better:



> no username shown on top menu

Good catch!

**Comment by almet** [comment]
neat :)

**Comment by n1k0** [comment]
Addressed @leplatrem nits, updated hosted instance. 

May I have a r+ (or more nits) from someone?

**Comment by Natim** [comment]
You can have a r+ from me yes :)

**Comment by Natim** [comment]
Maybe we can use the fxa:FxID as the username before we display the email?

**Comment by n1k0** [comment]
> Maybe we can use the fxa:FxID as the username before we display the email?

I prefer doing everything at once. Merging this.

**Comment by vanillajonathan** [comment]
Have this functionality been removed?

**Comment by Natim** [comment]
It has not, however you need to activate the kinto-fxa plugin on your service to see it

**Comment by vanillajonathan** [comment]
Ah, I see that it does not seem to be activated on https://kinto.github.io/kinto-admin/
Any reason why it is not activated?

**Comment by Natim** [comment]
You can use OpenID Conenct (Auth0) to try it.

**Pull request merged**
