### PR TITLE
package-lock.json is out of sync

### LINKED ISSUE #612: package-lock.json is out of sync
On master, if you start a fresh with `rm -fr node_modules && npm install` the `package-lock.json` is forced to change. That's wrong.

### PR DESCRIPTION
**Pull request by peterbe**
Fixes #612

### CODE REVIEW

**Comment by peterbe** [comment]
There is nothing to review. If this works in Travis (ideally, with a clean cache) *and* it works when someone does ...

```
git remote add peterbe https://github.com/peterbe/kinto-admin.git
git fetch peterbe
git checkout peterbe/612-package-lockjson-is-out-of-sync
rm -fr node_modules
npm install
git status
```

**Comment by Natim** [comment]
It didn't work locally:

```
--- a/package-lock.json
+++ b/package-lock.json
@@ -6993,12 +6993,14 @@
         "balanced-match": {
           "version": "1.0.0",
           "bundled": true,
-          "dev": true
+          "dev": true,
+          "optional": true
         },
         "brace-expansion": {
           "version": "1.1.11",
           "bundled": true,
           "dev": true,
+          "optional": true,
           "requires": {
             "balanced-match": "^1.0.0",
             "concat-map": "0.0.1"
@@ -7013,17 +7015,20 @@
         "code-point-at": {
           "version": "1.1.0",
           "bundled": true,
-          "dev": true
+          "dev": true,
+          "optional": true
         },
         "concat-map": {
           "version": "0.0.1",
           "bundled": true,
-          "dev": true
+          "dev": true,
+          "optional": true
         },
         "console-control-strings": {
           "version": "1.1.0",
           "bundled": true,
-          "dev": true
+          "dev": true,
+          "optional": true
         },
         "core-util-is": {
           "version": "1.0.2",
@@ -7140,7 +7145,8 @@
         "inherits": {
           "version": "2.0.3",
           "bundled": true,
-          "dev": true
+          "dev": true,
+          "optional": true
         },
         "ini": {
           "version": "1.3.5",
@@ -7152,6 +7158,7 @@
           "version": "1.0.0",
           "bundled": true,
           "dev": true,
+          "optional": true,
           "requires": {
             "number-is-nan": "^1.0.0"
           }
@@ -7166,6 +7173,7 @@
           "version": "3.0.4",
           "bundled": true,
           "dev": true,
+          "optional": true,
           "requires": {
             "brace-expansion": "^1.1.7"
           }
@@ -7173,12 +7181,14 @@
         "minimist": {
           "version": "0.0.8",
           "bundled": true,
-          "dev": true
+          "dev": true,
+          "optional": true
         },
         "minipass": {
           "version": "2.2.4",
           "bundled": true,
           "dev": true,
+          "optional": true,
           "requires": {
             "safe-buffer": "^5.1.1",
             "yallist": "^3.0.0"
@@ -7197,6 +7207,7 @@
           "version": "0.5.1",
           "bundled": true,
           "dev": true,
+          "optional": true,
           "requires": {
             "minimist": "0.0.8"
           }
@@ -7277,7 +7288,8 @@
         "number-is-nan": {
           "version": "1.0.1",
           "bundled": true,
-          "dev": true
+          "dev": true,
+          "optional": true
         },
         "object-assign": {
           "version": "4.1.1",
@@ -7289,6 +7301,7 @@
           "version": "1.4.0",
           "bundled": true,
           "dev": true,
+          "optional": true,
           "requires": {
             "wrappy": "1"
           }
@@ -7410,6 +7423,7 @@
           "version": "1.0.2",
           "bundled": true,
           "dev": true,
+          "optional": true,
           "requires": {
             "code-point-at": "^1.0.0",
             "is-fullwidth-code-point": "^1.0.0",
```

Can it be related to the version of npm that one uses?

**Comment by Natim** [comment]
I guess the addition are unrelated to your fix, since the hash actually don't change. Can you try with my commit to see if it changes on your side?

**Comment by leplatrem** [comment]
I also have these `optional: true` in #614 :disappointed:

**Comment by peterbe** [comment]
What??! What did you do @Natim? I built that `package-lock.json` using npm 6.2.0. Are you saying it becomes different if you use npm 6.4.1?? Sick.

**Pull request merged**
