### PR TITLE
Fixes #60: Improved conflict resolution UI.

### LINKED ISSUE #60: Render a diff for conflicting objects.

### PR DESCRIPTION
**Pull request by n1k0**
Refs #58, #60.

This attempts at iimproving the conflict resolution UI:

Note that this also addresses this comment https://github.com/Kinto/kinto-admin/issues/59#issuecomment-217804899.

r=? @glasserc @leplatrem @Natim

### CODE REVIEW

**Comment by glasserc** [comment]
I think you should reverse the directions of source and target. I don't have a rigorous justification, but on the left, I'd expect to see green corresponding to the local version, and I'd expect to see the remote version above the local version that "replaces" it.

**Comment by glasserc** [comment]
I'm also not crazy about the diff being "chunks" instead of individual properties.

**Comment by n1k0** [comment]
> I'm also not crazy about the diff being "chunks" instead of individual properties.

Yeah, I agree... I couldn't find any lib doing property-based diffs on npm, or the ones I found trying to were.. let's say they weren't really up to my expectations. We could probably spend some time writing our own, but that might get tricky when formatted arrays and deep nesting are involved.

If we could live with the current chunk-based diff approach, that'd probably save us some useful CPU cycles :) We could also spawn a new enhancement issue about it so we could land this (when it's ready) then iterate.

**Comment by n1k0** [comment]
This is now ready for final review. r=? @glasserc @leplatrem @Natim

**Comment by Natim** [comment]
If it is not possible to have red line on the left and green lines on the right, Is it possible to remove the diff altogether (red and green lines)?

**Comment by n1k0** [comment]
> Is it possible to remove the diff altogether (red and green lines)?

Sorry, I didn't undersand

**Comment by Natim** [comment]
Something like that: 
diff

Or if it is not possible the same thing without the + and colors.

**Comment by n1k0** [comment]
I still don't get it and am finding the mockup even more confusing, but that may just be because I'm hands deep into the current implementation and so I got used to it :D

Maybe what you're actually suggesting is to have a side by side diff view ala Eclipse or equivalent?

Sorry I'm really trying to understand :)

**Comment by Natim** [comment]
Yes basically my point is to have both records (the local one and the remote one) side by side with their properties sorted the same way so that it is easy to select one or the other.

If we can highlight properties that are different it is better but my point is to have the record in its entirety without mixed diff in it.

**Comment by n1k0** [comment]
> Yes basically my point is to have both records (the local one and the remote one) side by side with their properties sorted the same way so that it is easy to select one or the other.

We already have that in the default view, did you try the patch ? :)

> If we can highlight properties that are different

That's the purpose of the diff view, but I understand you'd like to have them highlighted in the default view. That's probably achievable for simple one-line properties but I fear it can get tricky with formatted arrays. I'll try and see how it goes though.

**Comment by Natim** [comment]
Oh I missed the button show diff :+1:  on the screenshot.let me try the patch :)

**Comment by Natim** [comment]
r+

**Pull request merged**
