### PR TITLE
Fix #318: querystring now takes resource_name into account

### LINKED ISSUE #318: [Signoff] Changes list view doesn't filter records properly
It appears that the HTTP request issued to the history endpoint doen't include the `resource_name` query string parameter: `/v1/buckets/staging/history?collection_id=gfx&_sort=-last_modified&_since=0`

So we end up with all information about the collection as well:

cc @leplatrem

### PR DESCRIPTION
**Pull request by leplatrem**
Fixes #318

### CODE REVIEW

**Comment by n1k0** [comment]
Just a day after thought, maybe we should add a few unit tests for these route hook functions somewhere?

**Comment by leplatrem** [comment]
Should we export them? Otherwise I have no idea how to test that.

**Comment by n1k0** [comment]
Yeah exporting them seems to be the easiest way to go

**Comment by n1k0** [comment]
LGTM r+ with a green build

**Pull request merged**
