### PR TITLE
Bucket data edition.

### PR DESCRIPTION
**Pull request by n1k0**
Refs #84. This basically allows editing bucket data (JSON properties) from the UI.

The patch is larger than expected because:

- it introduces a new store, actions and sagas for storing and handling the current selected bucket state;
- it refactors the way we preload resources when the current route changes;
- saga tests are really verbose.

#### Todo from @leplatrem 

- [x] Update bucket and collection name json schema field to add an appropriate validation regexp
- [x] Avoid stacking up error notifications

### CODE REVIEW

**Comment by n1k0** [comment]
Deployed the patch to gh-pages for easier QA.

**Comment by n1k0** [comment]
```
13:23:09 <•leplatrem> quand je vais dans Create
13:23:31 <•leplatrem> je saisis un nom pourrri qui passe pas: ça m'affiche une notif mais je récupère le form vide!
13:24:01 <•leplatrem> si j'ai saisi du json ça m'embete, je perds tout parce que j'ai mis un espace dans le nom du bucket
13:24:40 <•leplatrem> le 2eme, c'est que quand je re-submite, ça me vire pas la notif d'avant. Si je fais deux fois de suite un form pourri, j'ai deux notifs qui s'accumulent
```

**Comment by n1k0** [comment]
This is now ready for review; r=? @Natim @leplatrem @almet @glasserc

**Comment by Natim** [comment]
\o/ Genial

**Comment by n1k0** [comment]
Updated gh-pages with the latest version of the patch.

**Comment by Natim** [comment]
It looks good to me.

**Pull request merged**
