### PR TITLE
Fix some technical debt

### PR DESCRIPTION
**Pull request by n1k0**
Refs #204 and addresses a few other bits of technical debt.

- [x] Removed unused `ROUTE_LOAD_SUCCESS` action
- [x] Rename `Bucket` type to `BucketState`
- [x] Rename `Collection` type to `CollectionState`
- [x] Rename `Session` type to `SessionState`
- [x] Rename `SessionServerInfo` to `ServerInfo`
- [x] Update default collection records route to `/collection/:cid/records`
- [x] Isolate collection data in collection state
- [x] Drop unused collection state `bucket` property
- [x] Rename collection state `name` property to `id`
- [x] Rename bucket state `name` property to `id`

### CODE REVIEW

**Comment by leplatrem** [comment]
LG :)

**Comment by n1k0** [comment]
> LG :)

Not over :p

**Comment by n1k0** [comment]
May I request a review from @leplatrem? Would be greatly appreciated :)

**Comment by n1k0** [comment]
I'm gonna land this as I've started working on some other branches and don't want to waste too much time synchronizing them with this while stale.

**Pull request merged**
