### PR TITLE
Downgrade to history v4

### PR DESCRIPTION
**Pull request by leplatrem**
See https://github.com/supasate/connected-react-router/issues/312

### CODE REVIEW

**Review by grahamalama — COMMENTED** [review]
Can you think of a way we could write a test for this that fails with `history@^5` but passes with `history@^4` to prevent future regressions?

**Comment by leplatrem** [comment]
> Can you think of a way we could write a test for this that fails with history@^5 but passes with history@^4 to prevent future regressions?

Something around following links / navigation. I don't know yet whether this would require a full browser or not.

**Comment by grahamalama** [comment]
Alternatively, maybe we can upgrade our build process to use npm v7 because of how [peer dependencies](https://github.blog/2021-02-02-npm-7-is-now-generally-available/#peer-dependencies) are treated:
> In previous versions of npm (4-6), peer dependencies conflicts presented a warning that versions were not compatible, but would still install dependencies without an error. npm 7 will block installations if an upstream dependency conflict is present that cannot be automatically resolved.

**Comment by leplatrem** [comment]
Good catch! Yes! I was indeed wondering why peer deps were not blocking anything here

**Review by grahamalama — APPROVED** [review]

**Pull request merged**
