### PR TITLE
Fix #377, #378: Allow dropping edited resource properties.

### LINKED ISSUE #377: Remove property from existing entry in collection
For our A/B experiments we have a collection of entries that look like this (simplified):

```json
{
    "name":"offline-cache",
    "last_modified":1482264657139,
    "id":"5e4277e0-1029-ea14-1b74-5d25d301c5dc",
    "match": {
        "appId":"^org.mozilla.fennec.*$"
    }
}
```

Some experiments we limit to specific app versions using for example the "appId" property in the example above. If we decide to later remove this restriction then we can't do this with the web admin. We could clear it but then we still have this empty property in the JSON and we need to special case this situation in our app. Instead it would be super helpful to be able to remove a property (instead of just clearing it).

Workaround in Fennec:
https://bugzilla.mozilla.org/show_bug.cgi?id=1335355

### PR DESCRIPTION
**Pull request by n1k0**
Refs #377, #378. Deployed to gh-pages.

r? @leplatrem

### CODE REVIEW

**Comment by n1k0** [comment]
> (fields can be lost, and collection review data cannot be removed so it may fail)

I couldn't reproduce the loss of fields, can you point me at a reproducible scenario?

**Comment by leplatrem** [comment]
> can you point me at a reproducible scenario?

Indeed, I made a quick test and it seems to behave properly on collection metadata. How do we manage the difference between attributes that must removed versus. attributes that are missing from data and must remain intact ?

**Comment by n1k0** [comment]
> How do we manage the difference between attributes that must removed versus. attributes that are missing from data and must remain intact ?

It's because initial collection data are passed as *formData* to the form, with preexisting fields kept untouched though submitted, so they're sent as well. Dropping a value by clearing a text field works because we updated to rjsf v0.42.0 which supports this new feature.

**Pull request merged**
