### PR TITLE
Fix #949: fix history list from signoff diff details

### LINKED ISSUE #949: [signoff] History list in details view contains an extra record
On a signed collection

- clear a record
- click «view details» in the diff info
- the history list should contain one record, and now 2

### PR DESCRIPTION
**Pull request by leplatrem**
Fix #949

### CODE REVIEW

**Comment by leplatrem** [comment]
> Hmm... are kinto history entries not dated the same as the modifications they represent?

Nope the history entries have their own timestamps. But you're right I should give a detailed example (tomorrow)

**Comment by leplatrem** [comment]
Comment added https://github.com/Kinto/kinto-admin/issues/949#issuecomment-499036218

**Comment by glasserc** [comment]
Thanks for the detailed explanation. I kind of wish that history entries had the same timestamp as the record that had been modified, but maybe that's unreasonable.

**Comment by leplatrem** [comment]
> Thanks for the detailed explanation. I kind of wish that history entries had the same timestamp as the record that had been modified, but maybe that's unreasonable.

Well, they don't. 
But we have an excuse: timestamps are guarenteed to be unique per bucket/collection, whereas history entries are per bucket, which makes it difficult ;)

**Pull request merged**
