### PR TITLE
Fix #289: Render a loading spinner on bucket list load.

### LINKED ISSUE #289: Show loader in side bar

### PR DESCRIPTION
**Pull request by n1k0**
Refs #289, deployed to gh-pages for testing.

admin-sidebar-loader

### CODE REVIEW

**Comment by n1k0** [comment]
CI is failing because of a python error:



@leplatrem, @natim any idea?

**Comment by Natim** [comment]
Probably because you are running your tests on Kinto master with Python 2 instead of Python 3.

**Comment by leplatrem** [comment]
Nice! 

can you explain the stuff you removed (session busy?) please? (curiosity)

**Comment by leplatrem** [comment]
Ok current tests status is 

```
  447 passing (2s)

  1 failing

  1) collection sagas listNextRecords() Success should scroll to page bottom:

     TypeError: Cannot set property scrollHeight of [object Object] which has only a getter

      at Context.<anonymous> (test/sagas/collection_test.js:144:9)

```

**Comment by n1k0** [comment]
> can you explain the stuff you removed (session busy?) please? (curiosity)

I'm trying to move away from busy state setting trhough dedicated actions, and set the busy flag in the appropriate switch case in the reducer instead, as this has proven more explicit and reliable.

**Comment by n1k0** [comment]
> TypeError: Cannot set property scrollHeight of [object Object] which has only a getter

Wow now I'm really wondering why this happens only now, as we didn't upgrade any dependencies with this patch...

**Comment by n1k0** [comment]
This is especially strange as this doesn't happen locally for me.

**Pull request merged**
