### PR TITLE
Fix #299: Fix broken attachment creation.

### LINKED ISSUE #299: Error when creating a record with attachment only
Reproduce steps:
- version 1.4.0
- Create a collection with default schema and attachments enabled
- Create a record, do not fill anything, push create → OK
- Create a record, do not fill anything, browse and pick an attachment, push create → KO

Also, the error notification is empty: here, even if it's a bug, it should at least contain `Safe concurrency check requires a last_modified value`

capture d ecran de 2016-10-26 12-54-01

```
Error: Safe concurrency check requires a last_modified value.
Stack trace:
u@https://kinto.github.io/kinto-admin/bundle.js:51:31585
l</<.value@https://kinto.github.io/kinto-admin/bundle.js:52:11041
d/</<.get/r/<@https://kinto.github.io/kinto-admin/bundle.js:51:23645
Async*d/</<.get/r@https://kinto.github.io/kinto-admin/bundle.js:51:23425
O@https://kinto.github.io/kinto-admin/bundle.js:49:22520
_@https://kinto.github.io/kinto-admin/bundle.js:49:21591
r@https://kinto.github.io/kinto-admin/bundle.js:49:20326
l@https://kinto.github.io/kinto-admin/bundle.js:49:25653
T@https://kinto.github.io/kinto-admin/bundle.js:49:23153
_@https://kinto.github.io/kinto-admin/bundle.js:49:21678
r@https://kinto.github.io/kinto-admin/bundle.js:49:20326
n@https://kinto.github.io/kinto-admin/bundle.js:49:20995
S/i@https://kinto.github.io/kinto-admin/bundle.js:49:22184
n@https://kinto.github.io/kinto-admin/bundle.js:50:259
i/i<@https://kinto.github.io/kinto-admin/bundle.js:50:1102
t@https://kinto.github.io/kinto-admin/bundle.js:49:31847
e/</<@https://kinto.github.io/kinto-admin/bundle.js:50:4509
```

### PR DESCRIPTION
**Pull request by n1k0**
Not super proud with this one, though couldn't find any other way to perform safe creation with kinto-attachments. Thoughts @leplatrem?

### CODE REVIEW

**Comment by leplatrem** [comment]
Actually I would rather fix that in kinto-http.js instead...

**Comment by n1k0** [comment]
Makes sense, will do.

**Comment by n1k0** [comment]
:+1:

**Comment by Natim** [comment]
Well I didn't want it to squash the commit but it did. Sorry about that.

**Comment by n1k0** [comment]
On this project squashing is the norm, so that's fine.

**Pull request merged**
