### PR TITLE
Fix #387: Add a full collection changes diff view.

### LINKED ISSUE #387: The review process is currently not really usable
Today you have to look at the history but it really doesn't tells you much.
I would be nicer to see a full diff of what changed.

### PR DESCRIPTION
**Pull request by n1k0**
- [x] full diff view for a collection records list

### CODE REVIEW

**Comment by n1k0** [comment]
I'd appreciate early feedback from @leplatrem @natim @glasserc @gabisurita or anybody willing to :)

**Comment by Natim** [comment]
Nice +1

**Comment by n1k0** [comment]
After record deletion:

**Comment by Natim** [comment]
Record deletion is really confusing then, why is it green and not red?

**Comment by n1k0** [comment]
It really depends on the moment you compute the diff from. Here the diff is computed from a starting point where the record which has been deleted didn't exist at all, so there's no way the diff can reflect that. Here's a diff from the very last state before the record is deleted:

**Comment by Natim** [comment]
Ok makes sense.

**Comment by n1k0** [comment]
I've added dedicated navigation buttons to make the history list starting at a change specific timestamp, here's an animation:

tmp

I've deployed the patch to gh-pages so you can play with the feature.

**Comment by gabisurita** [comment]
👍

**Comment by leplatrem** [comment]
Looks nice!

µnit: are there loading spinners while filtering log on a particular entry?

**Comment by n1k0** [comment]
> µnit: are there loading spinners while filtering log on a particular entry?

https://github.com/Kinto/kinto-admin/pull/393/commits/157233f20f9ab6f32e0fdb84f873561e4b3e44ae

**Comment by n1k0** [comment]
final r=? @leplatrem @natim

**Comment by leplatrem** [comment]
👏

**Pull request merged**
