### PR TITLE
Fix history diff viewing

### LINKED ISSUE #562: Viewing history diff should have a scrollbar
Refs https://bugzilla.mozilla.org/show_bug.cgi?id=1471510

### PR DESCRIPTION
**Pull request by magopian**
Fixes #562

### CODE REVIEW

**Comment by magopian** [comment]
@glasserc this partially reverts what was done in https://github.com/Kinto/kinto-admin/commit/f2e9326dcabd571f0166b0ffdda26525f2db0226?w=1#diff-783a4918ddce584cff30089389577b76, I'm not sure why you made the change in the `HistoryTable` component, maybe I'm missing something?

**Comment by magopian** [comment]
I think I now understand why the change was made, and I need to find another way to fix it. Will ping you @glasserc whenever I have a solution.

**Comment by magopian** [comment]
Ok, I think I found a workaround to make flow happy, ping @glasserc.

**Comment by leplatrem** [comment]
you can post a screenshot to help figuring out the changes

**Comment by magopian** [comment]
Yeah @leplatrem the fix makes it display the diff taking the whole width of the table, as it used to:

screen shot 2018-06-29 at 17 56 03

**Comment by leplatrem** [comment]
Excellent thanks :)

**Pull request merged**
